In [2]:
import pandas as pd

### 강남구 취소일 배제, 22-23 추출

In [4]:
df = pd.read_csv('./data/gangnam.csv', encoding='cp949')

/var/folders/yl/ctrp4vjd3zn407qhh_nft51h0000gn/T/ipykernel_5108/2731320737.py:1: DtypeWarning: Columns (15,19,20) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('./data/gangnam.csv', encoding='cp949')

In [25]:
df

,접수연도,자치구코드,자치구명,법정동코드,법정동명,지번구분,지번구분명,본번,부번,건물명,...,물건금액(만원),건물면적(㎡),토지면적(㎡),층,권리구분,취소일,건축년도,건물용도,신고구분,신고한 개업공인중개사 시군구명
0,2023,11680,강남구,10100,역삼동,1.0,대지,774.0,34.0,리치웰빌라트2차,...,60000,47.42,29.78,6.0,NaN,NaN,2017.0,연립다세대,중개거래,서울 강남구
1,2023,11680,강남구,11800,도곡동,1.0,대지,961.0,0.0,현대아파트1동~3동,...,138600,84.96,0.00,7.0,NaN,NaN,1994.0,아파트,직거래,NaN
2,2023,11680,강남구,10700,신사동,1.0,대지,555.0,34.0,(555-34),...,19500,27.01,19.42,2.0,NaN,NaN,2011.0,연립다세대,직거래,NaN
3,2023,11680,강남구,10100,역삼동,1.0,대지,823.0,26.0,강남역두산위브센티움,...,21500,28.71,39.30,5.0,NaN,NaN,2004.0,오피스텔,중개거래,서울 강남구
4,2023,11680,강남구,11800,도곡동,1.0,대지,953.0,1.0,SK허브프리모,...,41000,33.80,0.00,17.0,NaN,NaN,2006.0,아파트,직거래,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
132733,2006,11680,강남구,10300,개포동,1.0,대지,655.0,1.0,개포현대200동,...,58000,82.20,NaN,8.0,NaN,NaN,1986.0,아파트,NaN,NaN
132734,2006,11680,강남구,10300,개포동,1.0,대지,656.0,0.0,시영,...,65000,51.18,NaN,3.0,NaN,NaN,1984.0,아파트,NaN,NaN
132735,2006,11680,강남구,10600,대치동,1.0,대지,65.0,0.0,쌍용대치2,...,80000,84.49,NaN,12.0,NaN,NaN,1983.0,아파트,NaN,NaN
132736,2006,11680,강남구,10600,대치동,1.0,대지,65.0,0.0,쌍용대치2,...,79750,84.49,NaN,6.0,NaN,NaN,1983.0,아파트,NaN,NaN
132737,2006,11680,강남구,10800,논현동,1.0,대지,22.0,0.0,신동아(22),...,19300,35.73,NaN,9.0,NaN,NaN,1997.0,아파트,NaN,NaN

In [26]:
# 드랍할 조건 설정
drop_condition = df['계약일'] > 20211231

# 조건에 맞지 않는 행 드랍
df_22_23 = df[drop_condition]

df_22_23

,접수연도,자치구코드,자치구명,법정동코드,법정동명,지번구분,지번구분명,본번,부번,건물명,...,물건금액(만원),건물면적(㎡),토지면적(㎡),층,권리구분,취소일,건축년도,건물용도,신고구분,신고한 개업공인중개사 시군구명
0,2023,11680,강남구,10100,역삼동,1.0,대지,774.0,34.0,리치웰빌라트2차,...,60000,47.42,29.78,6.0,NaN,NaN,2017.0,연립다세대,중개거래,서울 강남구
1,2023,11680,강남구,11800,도곡동,1.0,대지,961.0,0.0,현대아파트1동~3동,...,138600,84.96,0.00,7.0,NaN,NaN,1994.0,아파트,직거래,NaN
2,2023,11680,강남구,10700,신사동,1.0,대지,555.0,34.0,(555-34),...,19500,27.01,19.42,2.0,NaN,NaN,2011.0,연립다세대,직거래,NaN
3,2023,11680,강남구,10100,역삼동,1.0,대지,823.0,26.0,강남역두산위브센티움,...,21500,28.71,39.30,5.0,NaN,NaN,2004.0,오피스텔,중개거래,서울 강남구
4,2023,11680,강남구,11800,도곡동,1.0,대지,953.0,1.0,SK허브프리모,...,41000,33.80,0.00,17.0,NaN,NaN,2006.0,아파트,직거래,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13749,2022,11680,강남구,10100,역삼동,1.0,대지,837.0,18.0,강남역 서희스타힐스 오피스텔,...,18000,23.58,36.07,6.0,NaN,NaN,2012.0,오피스텔,중개거래,서울 강남구
13750,2022,11680,강남구,10100,역삼동,1.0,대지,837.0,18.0,강남역 서희스타힐스 오피스텔,...,25500,31.50,48.18,12.0,NaN,NaN,2012.0,오피스텔,중개거래,서울 강남구
13751,2022,11680,강남구,10100,역삼동,1.0,대지,837.0,18.0,강남역 서희스타힐스 오피스텔,...,25500,31.50,48.18,12.0,NaN,NaN,2012.0,오피스텔,중개거래,서울 강남구
13752,2022,11680,강남구,10100,역삼동,1.0,대지,837.0,18.0,강남역 서희스타힐스 오피스텔,...,25500,31.50,48.18,12.0,NaN,NaN,2012.0,오피스텔,중개거래,서울 강남구
13753,2022,11680,강남구,10100,역삼동,1.0,대지,837.0,18.0,강남역 서희스타힐스 오피스텔,...,25500,31.50,48.18,12.0,NaN,NaN,2012.0,오피스텔,중개거래,서울 강남구

In [27]:
df_22_23 = df_22_23[df_22_23['취소일'].isna()]
df_22_23

,접수연도,자치구코드,자치구명,법정동코드,법정동명,지번구분,지번구분명,본번,부번,건물명,...,물건금액(만원),건물면적(㎡),토지면적(㎡),층,권리구분,취소일,건축년도,건물용도,신고구분,신고한 개업공인중개사 시군구명
0,2023,11680,강남구,10100,역삼동,1.0,대지,774.0,34.0,리치웰빌라트2차,...,60000,47.42,29.78,6.0,NaN,NaN,2017.0,연립다세대,중개거래,서울 강남구
1,2023,11680,강남구,11800,도곡동,1.0,대지,961.0,0.0,현대아파트1동~3동,...,138600,84.96,0.00,7.0,NaN,NaN,1994.0,아파트,직거래,NaN
2,2023,11680,강남구,10700,신사동,1.0,대지,555.0,34.0,(555-34),...,19500,27.01,19.42,2.0,NaN,NaN,2011.0,연립다세대,직거래,NaN
3,2023,11680,강남구,10100,역삼동,1.0,대지,823.0,26.0,강남역두산위브센티움,...,21500,28.71,39.30,5.0,NaN,NaN,2004.0,오피스텔,중개거래,서울 강남구
4,2023,11680,강남구,11800,도곡동,1.0,대지,953.0,1.0,SK허브프리모,...,41000,33.80,0.00,17.0,NaN,NaN,2006.0,아파트,직거래,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13749,2022,11680,강남구,10100,역삼동,1.0,대지,837.0,18.0,강남역 서희스타힐스 오피스텔,...,18000,23.58,36.07,6.0,NaN,NaN,2012.0,오피스텔,중개거래,서울 강남구
13750,2022,11680,강남구,10100,역삼동,1.0,대지,837.0,18.0,강남역 서희스타힐스 오피스텔,...,25500,31.50,48.18,12.0,NaN,NaN,2012.0,오피스텔,중개거래,서울 강남구
13751,2022,11680,강남구,10100,역삼동,1.0,대지,837.0,18.0,강남역 서희스타힐스 오피스텔,...,25500,31.50,48.18,12.0,NaN,NaN,2012.0,오피스텔,중개거래,서울 강남구
13752,2022,11680,강남구,10100,역삼동,1.0,대지,837.0,18.0,강남역 서희스타힐스 오피스텔,...,25500,31.50,48.18,12.0,NaN,NaN,2012.0,오피스텔,중개거래,서울 강남구
13753,2022,11680,강남구,10100,역삼동,1.0,대지,837.0,18.0,강남역 서희스타힐스 오피스텔,...,25500,31.50,48.18,12.0,NaN,NaN,2012.0,오피스텔,중개거래,서울 강남구

In [28]:
# file 내보내기
file_path = './data/gangnam_22to23.csv'
df_22_23.to_csv(file_path,index=False)

### 양천구 취소일 배제, 22-23 출력

In [ ]:
yangcheon = pd.read_csv('./data/yangcheon.csv', encoding='cp949')
yangcheon

/var/folders/yl/ctrp4vjd3zn407qhh_nft51h0000gn/T/ipykernel_89167/1776251765.py:1: DtypeWarning: Columns (19,20) have mixed types. Specify dtype option on import or set low_memory=False.
  yangcheon = pd.read_csv('./yangcheon.csv', encoding='cp949')

,접수연도,자치구코드,자치구명,법정동코드,법정동명,지번구분,지번구분명,본번,부번,건물명,...,물건금액(만원),건물면적(㎡),토지면적(㎡),층,권리구분,취소일,건축년도,건물용도,신고구분,신고한 개업공인중개사 시군구명
0,2023,11470,양천구,10100,신정동,1.0,대지,329.0,0.0,목동신시가지14,...,160000,84.87,0.00,7.0,NaN,NaN,1987.0,아파트,중개거래,서울 양천구
1,2023,11470,양천구,10100,신정동,1.0,대지,973.0,39.0,신성스카이뷰,...,34000,26.97,10.22,5.0,NaN,NaN,2020.0,연립다세대,중개거래,서울 중구
2,2023,11470,양천구,10300,신월동,1.0,대지,231.0,10.0,하나IPARK,...,32800,47.00,27.78,6.0,NaN,NaN,2015.0,연립다세대,직거래,NaN
3,2023,11470,양천구,10100,신정동,1.0,대지,329.0,0.0,목동신시가지14,...,140000,71.40,0.00,7.0,NaN,NaN,1987.0,아파트,중개거래,서울 양천구
4,2023,11470,양천구,10100,신정동,1.0,대지,329.0,0.0,목동신시가지14,...,112000,55.02,0.00,13.0,NaN,NaN,1987.0,아파트,중개거래,서울 양천구
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
126847,2006,11470,양천구,10200,목동,1.0,대지,907.0,0.0,현대월드타워,...,7970,38.22,54.78,17.0,NaN,NaN,1999.0,오피스텔,NaN,NaN
126848,2006,11470,양천구,10200,목동,1.0,대지,934.0,0.0,금호1,...,31000,59.88,NaN,10.0,NaN,NaN,1997.0,아파트,NaN,NaN
126849,2006,11470,양천구,10100,신정동,1.0,대지,326.0,0.0,목동신시가지12,...,43000,71.64,NaN,5.0,NaN,NaN,1988.0,아파트,NaN,NaN
126850,2006,11470,양천구,10200,목동,1.0,대지,925.0,0.0,목동신시가지7,...,31000,53.88,NaN,11.0,NaN,NaN,1986.0,아파트,NaN,NaN
126851,2006,11470,양천구,10100,신정동,1.0,대지,312.0,0.0,목동신시가지9,...,33300,53.82,NaN,7.0,NaN,NaN,1987.0,아파트,NaN,NaN

In [ ]:
# 드랍할 조건 설정
drop_condition = yangcheon['계약일'] > 20211231

# 조건에 맞지 않는 행 드랍
yangcheon_22_23 = yangcheon[drop_condition]

yangcheon_22_23

,접수연도,자치구코드,자치구명,법정동코드,법정동명,지번구분,지번구분명,본번,부번,건물명,...,물건금액(만원),건물면적(㎡),토지면적(㎡),층,권리구분,취소일,건축년도,건물용도,신고구분,신고한 개업공인중개사 시군구명
0,2023,11470,양천구,10100,신정동,1.0,대지,329.0,0.0,목동신시가지14,...,160000,84.87,0.00,7.0,NaN,NaN,1987.0,아파트,중개거래,서울 양천구
1,2023,11470,양천구,10100,신정동,1.0,대지,973.0,39.0,신성스카이뷰,...,34000,26.97,10.22,5.0,NaN,NaN,2020.0,연립다세대,중개거래,서울 중구
2,2023,11470,양천구,10300,신월동,1.0,대지,231.0,10.0,하나IPARK,...,32800,47.00,27.78,6.0,NaN,NaN,2015.0,연립다세대,직거래,NaN
3,2023,11470,양천구,10100,신정동,1.0,대지,329.0,0.0,목동신시가지14,...,140000,71.40,0.00,7.0,NaN,NaN,1987.0,아파트,중개거래,서울 양천구
4,2023,11470,양천구,10100,신정동,1.0,대지,329.0,0.0,목동신시가지14,...,112000,55.02,0.00,13.0,NaN,NaN,1987.0,아파트,중개거래,서울 양천구
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9803,2022,11470,양천구,10300,신월동,1.0,대지,18.0,14.0,아크로힐즈,...,22000,31.09,20.47,4.0,NaN,NaN,2017.0,연립다세대,중개거래,서울 강서구
9804,2022,11470,양천구,10300,신월동,1.0,대지,957.0,5.0,효석주택,...,25500,32.01,22.43,3.0,NaN,NaN,1989.0,연립다세대,중개거래,서울 양천구
9805,2022,11470,양천구,10300,신월동,1.0,대지,957.0,5.0,효석주택,...,25500,32.01,22.43,3.0,NaN,NaN,1989.0,연립다세대,중개거래,서울 양천구
9806,2022,11470,양천구,10300,신월동,1.0,대지,18.0,14.0,아크로힐즈,...,22000,31.09,20.47,4.0,NaN,NaN,2017.0,연립다세대,중개거래,서울 강서구
9807,2022,11470,양천구,10300,신월동,1.0,대지,18.0,14.0,아크로힐즈,...,22000,31.09,20.47,4.0,NaN,NaN,2017.0,연립다세대,중개거래,서울 강서구

In [ ]:
yangcheon_22_23 = yangcheon_22_23[yangcheon_22_23['취소일'].isna()]
yangcheon_22_23

,접수연도,자치구코드,자치구명,법정동코드,법정동명,지번구분,지번구분명,본번,부번,건물명,...,물건금액(만원),건물면적(㎡),토지면적(㎡),층,권리구분,취소일,건축년도,건물용도,신고구분,신고한 개업공인중개사 시군구명
0,2023,11470,양천구,10100,신정동,1.0,대지,329.0,0.0,목동신시가지14,...,160000,84.87,0.00,7.0,NaN,NaN,1987.0,아파트,중개거래,서울 양천구
1,2023,11470,양천구,10100,신정동,1.0,대지,973.0,39.0,신성스카이뷰,...,34000,26.97,10.22,5.0,NaN,NaN,2020.0,연립다세대,중개거래,서울 중구
2,2023,11470,양천구,10300,신월동,1.0,대지,231.0,10.0,하나IPARK,...,32800,47.00,27.78,6.0,NaN,NaN,2015.0,연립다세대,직거래,NaN
3,2023,11470,양천구,10100,신정동,1.0,대지,329.0,0.0,목동신시가지14,...,140000,71.40,0.00,7.0,NaN,NaN,1987.0,아파트,중개거래,서울 양천구
4,2023,11470,양천구,10100,신정동,1.0,대지,329.0,0.0,목동신시가지14,...,112000,55.02,0.00,13.0,NaN,NaN,1987.0,아파트,중개거래,서울 양천구
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9803,2022,11470,양천구,10300,신월동,1.0,대지,18.0,14.0,아크로힐즈,...,22000,31.09,20.47,4.0,NaN,NaN,2017.0,연립다세대,중개거래,서울 강서구
9804,2022,11470,양천구,10300,신월동,1.0,대지,957.0,5.0,효석주택,...,25500,32.01,22.43,3.0,NaN,NaN,1989.0,연립다세대,중개거래,서울 양천구
9805,2022,11470,양천구,10300,신월동,1.0,대지,957.0,5.0,효석주택,...,25500,32.01,22.43,3.0,NaN,NaN,1989.0,연립다세대,중개거래,서울 양천구
9806,2022,11470,양천구,10300,신월동,1.0,대지,18.0,14.0,아크로힐즈,...,22000,31.09,20.47,4.0,NaN,NaN,2017.0,연립다세대,중개거래,서울 강서구
9807,2022,11470,양천구,10300,신월동,1.0,대지,18.0,14.0,아크로힐즈,...,22000,31.09,20.47,4.0,NaN,NaN,2017.0,연립다세대,중개거래,서울 강서구

In [ ]:
# file 내보내기
file_path = './data/yangcheon_22to23.csv'
yangcheon_22_23.to_csv(file_path,index=False)

### 양천구 취소일 배제, 21 출력

In [3]:
yangcheon = pd.read_csv('./data/yangcheon.csv', encoding='cp949')
yangcheon

/var/folders/yl/ctrp4vjd3zn407qhh_nft51h0000gn/T/ipykernel_39685/1752811412.py:1: DtypeWarning: Columns (19,20) have mixed types. Specify dtype option on import or set low_memory=False.
  yangcheon = pd.read_csv('./data/yangcheon.csv', encoding='cp949')

,접수연도,자치구코드,자치구명,법정동코드,법정동명,지번구분,지번구분명,본번,부번,건물명,...,물건금액(만원),건물면적(㎡),토지면적(㎡),층,권리구분,취소일,건축년도,건물용도,신고구분,신고한 개업공인중개사 시군구명
0,2023,11470,양천구,10100,신정동,1.0,대지,329.0,0.0,목동신시가지14,...,160000,84.87,0.00,7.0,NaN,NaN,1987.0,아파트,중개거래,서울 양천구
1,2023,11470,양천구,10100,신정동,1.0,대지,973.0,39.0,신성스카이뷰,...,34000,26.97,10.22,5.0,NaN,NaN,2020.0,연립다세대,중개거래,서울 중구
2,2023,11470,양천구,10300,신월동,1.0,대지,231.0,10.0,하나IPARK,...,32800,47.00,27.78,6.0,NaN,NaN,2015.0,연립다세대,직거래,NaN
3,2023,11470,양천구,10100,신정동,1.0,대지,329.0,0.0,목동신시가지14,...,140000,71.40,0.00,7.0,NaN,NaN,1987.0,아파트,중개거래,서울 양천구
4,2023,11470,양천구,10100,신정동,1.0,대지,329.0,0.0,목동신시가지14,...,112000,55.02,0.00,13.0,NaN,NaN,1987.0,아파트,중개거래,서울 양천구
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
126847,2006,11470,양천구,10200,목동,1.0,대지,907.0,0.0,현대월드타워,...,7970,38.22,54.78,17.0,NaN,NaN,1999.0,오피스텔,NaN,NaN
126848,2006,11470,양천구,10200,목동,1.0,대지,934.0,0.0,금호1,...,31000,59.88,NaN,10.0,NaN,NaN,1997.0,아파트,NaN,NaN
126849,2006,11470,양천구,10100,신정동,1.0,대지,326.0,0.0,목동신시가지12,...,43000,71.64,NaN,5.0,NaN,NaN,1988.0,아파트,NaN,NaN
126850,2006,11470,양천구,10200,목동,1.0,대지,925.0,0.0,목동신시가지7,...,31000,53.88,NaN,11.0,NaN,NaN,1986.0,아파트,NaN,NaN
126851,2006,11470,양천구,10100,신정동,1.0,대지,312.0,0.0,목동신시가지9,...,33300,53.82,NaN,7.0,NaN,NaN,1987.0,아파트,NaN,NaN

In [4]:
# 드랍할 조건 설정
drop_condition1 = (yangcheon['계약일'] > 20191231)
drop_condition2 = (yangcheon['계약일'] <= 20201231)
# 조건에 맞지 않는 행 드랍
yangcheon_21 = yangcheon[drop_condition1][drop_condition2]

yangcheon_21

/var/folders/yl/ctrp4vjd3zn407qhh_nft51h0000gn/T/ipykernel_39685/88486235.py:5: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  yangcheon_21 = yangcheon[drop_condition1][drop_condition2]

,접수연도,자치구코드,자치구명,법정동코드,법정동명,지번구분,지번구분명,본번,부번,건물명,...,물건금액(만원),건물면적(㎡),토지면적(㎡),층,권리구분,취소일,건축년도,건물용도,신고구분,신고한 개업공인중개사 시군구명
15996,2021,11470,양천구,10200,목동,1.0,대지,780.0,4.0,성준빌라,...,19000,49.74,19.34,1.0,NaN,NaN,1997.0,연립다세대,NaN,NaN
15997,2021,11470,양천구,10100,신정동,1.0,대지,319.0,0.0,우림필유,...,77500,76.35,90.44,7.0,NaN,NaN,2004.0,오피스텔,NaN,NaN
15998,2021,11470,양천구,10100,신정동,1.0,대지,326.0,0.0,목동신시가지12,...,133000,71.64,NaN,9.0,NaN,NaN,1988.0,아파트,NaN,NaN
15999,2021,11470,양천구,10100,신정동,1.0,대지,1318.0,0.0,이펜하우스5단지,...,99000,114.73,0.00,9.0,NaN,NaN,2011.0,아파트,NaN,NaN
16000,2021,11470,양천구,10100,신정동,1.0,대지,337.0,0.0,목동우성2,...,126500,113.91,0.00,6.0,NaN,NaN,2000.0,아파트,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24733,2020,11470,양천구,10300,신월동,1.0,대지,935.0,2.0,경인주택(라동),...,7500,42.18,36.34,-1.0,NaN,NaN,1986.0,연립다세대,NaN,NaN
24734,2020,11470,양천구,10300,신월동,1.0,대지,241.0,13.0,트라움하우스(241-13),...,19400,50.76,29.21,2.0,NaN,NaN,2013.0,연립다세대,NaN,NaN
24735,2020,11470,양천구,10300,신월동,1.0,대지,420.0,14.0,삼성 B,...,12200,41.16,31.22,3.0,NaN,NaN,1988.0,연립다세대,NaN,NaN
24736,2020,11470,양천구,10200,목동,1.0,대지,941.0,0.0,대원칸타빌2,...,98000,84.98,NaN,14.0,NaN,NaN,2003.0,아파트,NaN,NaN
24737,2020,11470,양천구,10200,목동,1.0,대지,763.0,1.0,목동성원,...,73500,59.85,NaN,13.0,NaN,NaN,2000.0,아파트,NaN,NaN

In [5]:
yangcheon_21 = yangcheon_21[yangcheon_21['취소일'].isna()]
yangcheon_21

,접수연도,자치구코드,자치구명,법정동코드,법정동명,지번구분,지번구분명,본번,부번,건물명,...,물건금액(만원),건물면적(㎡),토지면적(㎡),층,권리구분,취소일,건축년도,건물용도,신고구분,신고한 개업공인중개사 시군구명
15996,2021,11470,양천구,10200,목동,1.0,대지,780.0,4.0,성준빌라,...,19000,49.74,19.34,1.0,NaN,NaN,1997.0,연립다세대,NaN,NaN
15997,2021,11470,양천구,10100,신정동,1.0,대지,319.0,0.0,우림필유,...,77500,76.35,90.44,7.0,NaN,NaN,2004.0,오피스텔,NaN,NaN
15998,2021,11470,양천구,10100,신정동,1.0,대지,326.0,0.0,목동신시가지12,...,133000,71.64,NaN,9.0,NaN,NaN,1988.0,아파트,NaN,NaN
15999,2021,11470,양천구,10100,신정동,1.0,대지,1318.0,0.0,이펜하우스5단지,...,99000,114.73,0.00,9.0,NaN,NaN,2011.0,아파트,NaN,NaN
16000,2021,11470,양천구,10100,신정동,1.0,대지,337.0,0.0,목동우성2,...,126500,113.91,0.00,6.0,NaN,NaN,2000.0,아파트,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24733,2020,11470,양천구,10300,신월동,1.0,대지,935.0,2.0,경인주택(라동),...,7500,42.18,36.34,-1.0,NaN,NaN,1986.0,연립다세대,NaN,NaN
24734,2020,11470,양천구,10300,신월동,1.0,대지,241.0,13.0,트라움하우스(241-13),...,19400,50.76,29.21,2.0,NaN,NaN,2013.0,연립다세대,NaN,NaN
24735,2020,11470,양천구,10300,신월동,1.0,대지,420.0,14.0,삼성 B,...,12200,41.16,31.22,3.0,NaN,NaN,1988.0,연립다세대,NaN,NaN
24736,2020,11470,양천구,10200,목동,1.0,대지,941.0,0.0,대원칸타빌2,...,98000,84.98,NaN,14.0,NaN,NaN,2003.0,아파트,NaN,NaN
24737,2020,11470,양천구,10200,목동,1.0,대지,763.0,1.0,목동성원,...,73500,59.85,NaN,13.0,NaN,NaN,2000.0,아파트,NaN,NaN

In [6]:
# file 내보내기
file_path = './data/yangcheon_20.csv'
yangcheon_21.to_csv(file_path,index=False)

### 강남구 취소일 배제, 21 추출

In [7]:
df = pd.read_csv('./data/gangnam.csv', encoding='cp949')

/var/folders/yl/ctrp4vjd3zn407qhh_nft51h0000gn/T/ipykernel_39685/2731320737.py:1: DtypeWarning: Columns (15,19,20) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('./data/gangnam.csv', encoding='cp949')

In [9]:
df

,접수연도,자치구코드,자치구명,법정동코드,법정동명,지번구분,지번구분명,본번,부번,건물명,...,물건금액(만원),건물면적(㎡),토지면적(㎡),층,권리구분,취소일,건축년도,건물용도,신고구분,신고한 개업공인중개사 시군구명
0,2023,11680,강남구,10100,역삼동,1.0,대지,774.0,34.0,리치웰빌라트2차,...,60000,47.42,29.78,6.0,NaN,NaN,2017.0,연립다세대,중개거래,서울 강남구
1,2023,11680,강남구,11800,도곡동,1.0,대지,961.0,0.0,현대아파트1동~3동,...,138600,84.96,0.00,7.0,NaN,NaN,1994.0,아파트,직거래,NaN
2,2023,11680,강남구,10700,신사동,1.0,대지,555.0,34.0,(555-34),...,19500,27.01,19.42,2.0,NaN,NaN,2011.0,연립다세대,직거래,NaN
3,2023,11680,강남구,10100,역삼동,1.0,대지,823.0,26.0,강남역두산위브센티움,...,21500,28.71,39.30,5.0,NaN,NaN,2004.0,오피스텔,중개거래,서울 강남구
4,2023,11680,강남구,11800,도곡동,1.0,대지,953.0,1.0,SK허브프리모,...,41000,33.80,0.00,17.0,NaN,NaN,2006.0,아파트,직거래,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
132733,2006,11680,강남구,10300,개포동,1.0,대지,655.0,1.0,개포현대200동,...,58000,82.20,NaN,8.0,NaN,NaN,1986.0,아파트,NaN,NaN
132734,2006,11680,강남구,10300,개포동,1.0,대지,656.0,0.0,시영,...,65000,51.18,NaN,3.0,NaN,NaN,1984.0,아파트,NaN,NaN
132735,2006,11680,강남구,10600,대치동,1.0,대지,65.0,0.0,쌍용대치2,...,80000,84.49,NaN,12.0,NaN,NaN,1983.0,아파트,NaN,NaN
132736,2006,11680,강남구,10600,대치동,1.0,대지,65.0,0.0,쌍용대치2,...,79750,84.49,NaN,6.0,NaN,NaN,1983.0,아파트,NaN,NaN
132737,2006,11680,강남구,10800,논현동,1.0,대지,22.0,0.0,신동아(22),...,19300,35.73,NaN,9.0,NaN,NaN,1997.0,아파트,NaN,NaN

In [10]:
# 드랍할 조건 설정
drop_condition1 = (df['계약일'] > 20191231)
drop_condition2 = (df['계약일'] <= 20201231)

# 조건에 맞지 않는 행 드랍
df_21 = df[drop_condition1][drop_condition2]

df_21

/var/folders/yl/ctrp4vjd3zn407qhh_nft51h0000gn/T/ipykernel_39685/3861781944.py:6: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_21 = df[drop_condition1][drop_condition2]

,접수연도,자치구코드,자치구명,법정동코드,법정동명,지번구분,지번구분명,본번,부번,건물명,...,물건금액(만원),건물면적(㎡),토지면적(㎡),층,권리구분,취소일,건축년도,건물용도,신고구분,신고한 개업공인중개사 시군구명
19846,2021,11680,강남구,11800,도곡동,1.0,대지,953.0,1.0,SK허브프리모,...,90000,67.57,0.00,5.0,NaN,NaN,2006.0,아파트,NaN,NaN
19847,2021,11680,강남구,10800,논현동,1.0,대지,107.0,16.0,리안,...,14674,14.09,7.54,1.0,NaN,20210426.0,2013.0,연립다세대,NaN,NaN
19848,2021,11680,강남구,11500,수서동,1.0,대지,746.0,0.0,까치마을,...,101000,39.60,0.00,10.0,NaN,NaN,1993.0,아파트,NaN,NaN
19849,2021,11680,강남구,11800,도곡동,1.0,대지,467.0,7.0,아카데미스위트1,...,208000,122.07,0.00,18.0,NaN,NaN,2004.0,아파트,NaN,NaN
19850,2021,11680,강남구,10100,역삼동,NaN,NaN,NaN,NaN,NaN,...,439000,494.42,245.30,NaN,NaN,NaN,2003.0,단독다가구,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26566,2020,11680,강남구,10600,대치동,1.0,대지,943.0,24.0,신안메트로칸,...,24500,27.09,39.13,16.0,NaN,NaN,2004.0,오피스텔,NaN,NaN
26567,2020,11680,강남구,11800,도곡동,1.0,대지,467.0,24.0,우성캐릭터199,...,170000,132.94,NaN,5.0,NaN,NaN,1998.0,아파트,NaN,NaN
26568,2020,11680,강남구,10600,대치동,1.0,대지,888.0,0.0,대치아이파크,...,300000,114.97,0.00,10.0,NaN,NaN,2008.0,아파트,NaN,NaN
26569,2020,11680,강남구,10600,대치동,1.0,대지,902.0,0.0,포스코더샵,...,247000,139.54,0.00,3.0,NaN,NaN,2004.0,아파트,NaN,NaN
26570,2020,11680,강남구,10600,대치동,1.0,대지,889.0,5.0,샹제리제센터(889-5),...,23300,35.70,35.70,14.0,NaN,NaN,1990.0,오피스텔,NaN,NaN

In [11]:
df_21 = df_21[df_21['취소일'].isna()]
df_21

,접수연도,자치구코드,자치구명,법정동코드,법정동명,지번구분,지번구분명,본번,부번,건물명,...,물건금액(만원),건물면적(㎡),토지면적(㎡),층,권리구분,취소일,건축년도,건물용도,신고구분,신고한 개업공인중개사 시군구명
19846,2021,11680,강남구,11800,도곡동,1.0,대지,953.0,1.0,SK허브프리모,...,90000,67.57,0.00,5.0,NaN,NaN,2006.0,아파트,NaN,NaN
19848,2021,11680,강남구,11500,수서동,1.0,대지,746.0,0.0,까치마을,...,101000,39.60,0.00,10.0,NaN,NaN,1993.0,아파트,NaN,NaN
19849,2021,11680,강남구,11800,도곡동,1.0,대지,467.0,7.0,아카데미스위트1,...,208000,122.07,0.00,18.0,NaN,NaN,2004.0,아파트,NaN,NaN
19850,2021,11680,강남구,10100,역삼동,NaN,NaN,NaN,NaN,NaN,...,439000,494.42,245.30,NaN,NaN,NaN,2003.0,단독다가구,NaN,NaN
19851,2021,11680,강남구,10100,역삼동,1.0,대지,707.0,1.0,두꺼비빌딩,...,20000,34.02,47.83,15.0,NaN,NaN,1990.0,오피스텔,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26566,2020,11680,강남구,10600,대치동,1.0,대지,943.0,24.0,신안메트로칸,...,24500,27.09,39.13,16.0,NaN,NaN,2004.0,오피스텔,NaN,NaN
26567,2020,11680,강남구,11800,도곡동,1.0,대지,467.0,24.0,우성캐릭터199,...,170000,132.94,NaN,5.0,NaN,NaN,1998.0,아파트,NaN,NaN
26568,2020,11680,강남구,10600,대치동,1.0,대지,888.0,0.0,대치아이파크,...,300000,114.97,0.00,10.0,NaN,NaN,2008.0,아파트,NaN,NaN
26569,2020,11680,강남구,10600,대치동,1.0,대지,902.0,0.0,포스코더샵,...,247000,139.54,0.00,3.0,NaN,NaN,2004.0,아파트,NaN,NaN
26570,2020,11680,강남구,10600,대치동,1.0,대지,889.0,5.0,샹제리제센터(889-5),...,23300,35.70,35.70,14.0,NaN,NaN,1990.0,오피스텔,NaN,NaN

In [12]:
# file 내보내기
file_path = './data/gangnam_20.csv'
df_21.to_csv(file_path,index=False)